# This file can be run using the "REST Client" VSCode extension,
# making testing as easy as clicking one of the requests,
# without having to jump back and forth to different tabs
# within PostMan, etc.


### vars

@host = http://localhost:5000

@filename = test.txt
@testdirname = testdir01

@file = ./test-files/{{filename}}
@fileInDir = ./test-files/{{testdirname}}/{{filename}}
# @file = ./test-files/empty.txt
# @file = ./TestProject_2024.zip




### Get list of files+dirs
GET {{host}}/api/dir
content-type: application/json


### Upload a file
POST {{host}}/api/dir/upload
# content-type: application/json
content-type: multipart/form-data; boundary=FileBoundary

--FileBoundary
Content-Disposition: form-data; name="file"; filename="{{file}}"
Content-Type: text/plain

< {{file}}
--FileBoundary--


### Download a file
GET {{host}}/api/dir/download/{{file}}


### Add a directory
POST {{host}}/api/dir/create
content-type: application/json

{
  "dirname": "{{testdirname}}"
}


### Move a file
POST {{host}}/api/dir/move
content-type: application/json

{
  "filePath": "{{testdirname}}/{{filename}}",
  "newPath": "{{testdirname}}/{{filename}}.bak"
}


### Copy a file
POST {{host}}/api/dir/copy
content-type: application/json

# {
#   "filePath": "{{filename}}",
#   "newPath": "{{testdirname}}/{{filename}}"
# }
{
  "filePath": "{{testdirname}}/{{filename}}.bak",
  "newPath": "{{testdirname}}/{{filename}}"
}


### Delete a file
POST {{host}}/api/dir/delete
content-type: application/json

{
  "filepath": "{{testdirname}}/{{filename}}.bak"
}
